# Generated by Django 4.2.7 on 2026-01-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('change_type', models.CharField(max_length=50)),
                ('confidence_score', models.IntegerField()),
                ('source_url', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_admin.exam')),
            ],
            options={
                'db_table': 'status_change_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('page_views', models.IntegerField(default=0)),
                ('needs_regeneration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_admin.exam')),
            ],
            options={
                'db_table': 'page_metadata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls_to_monitor', models.JSONField()),
                ('check_frequency_minutes', models.IntegerField()),
                ('priority', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_admin.exam')),
            ],
            options={
                'db_table': 'monitoring_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManualReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_admin.statuschangeevent')),
            ],
            options={
                'db_table': 'manual_review_queue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('official_link', models.TextField(blank=True, null=True)),
                ('pdf_link', models.TextField(blank=True, null=True)),
                ('total_vacancies', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_admin.exam')),
            ],
            options={
                'db_table': 'exam_events',
                'managed': True,
            },
        ),
    ]
