# Generated by Django 6.0.1 on 2026-02-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_name', models.CharField(max_length=100)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('items_scraped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraper_logs',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='examevent',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examevent',
            name='download_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemetadata',
            name='canonical_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemetadata',
            name='last_crawled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemetadata',
            name='schema_markup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='organization',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='examevent',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core_admin.exam'),
        ),
        migrations.AlterField(
            model_name='examevent',
            name='status',
            field=models.CharField(db_index=True, default='upcoming', max_length=50),
        ),
        migrations.AlterField(
            model_name='examevent',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pagemetadata',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagemetadata',
            name='slug',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='pagemetadata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('age_relaxation', models.JSONField(blank=True, null=True)),
                ('education_qualification', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('additional_criteria', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='core_admin.exam')),
            ],
            options={
                'db_table': 'eligibility',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, null=True)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marking_details', models.TextField(blank=True, null=True)),
                ('exam_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('pattern_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='core_admin.exam')),
            ],
            options={
                'db_table': 'exam_patterns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField(blank=True, null=True)),
                ('cutoff_general', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cutoff_obc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cutoff_sc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cutoff_st', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cutoff_ews', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_appeared', models.IntegerField(blank=True, null=True)),
                ('total_qualified', models.IntegerField(blank=True, null=True)),
                ('result_pdf_link', models.TextField(blank=True, null=True)),
                ('additional_cutoffs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core_admin.examevent')),
            ],
            options={
                'db_table': 'results',
                'managed': True,
            },
        ),
    ]
